[WIP] Show some formatting love to 'O' in OCaml
ocaml-ppx/ocamlformat pull request #1569
Opened 2020-12-10 12:06 UTC by bikallem

This is a WIP PR attempting to format OCaml `object ... end` syntactical structures. The scope of this PR is to format `class_structure` items (`class_field`s) the same was as `structure_item`s in a module.

I am opening this PR as a WIP and would appreciate pointers, feedback as to the implementation details. The implementation details follows closely the same mechanism as `structure_item`. 

- [ ] Make current tests pass
- [ ] Possibly add new tests ?

I want to address `class_type` formatting in separate PR. 

Thanks.

2020-12-10 14:45 UTC, bikallem commented
There's one test failing. However, that seems to exist in `master` and is to this change. Here is the snippet below,

```
--- a/test/passing/invalid_docstring.ml.ref
+++ b/test/passing/invalid_docstring.ml.output
@@ -1,4 +1,7 @@
 Warning: Invalid documentation comment:
-File "invalid_docstring.ml", line 1, characters 0-7:
-comment could not be parsed
+File "invalid_docstring.ml", line 1, characters 5-5:
+End of text is not allowed in '{v ... v}' (verbatim text).
+Warning: Invalid documentation comment:
+File "invalid_docstring.ml", line 1, characters 3-5:
+'{v ... v}' (verbatim text) should not be empty.
 (**{v*)

```

2020-12-11 12:27 UTC, bikallem commented
@gpetiot  Ready for review, thanks.

2020-12-15 10:46 UTC, gpetiot requested changes
Thanks for your contribution! it's indeed better to add some consistency with structure/signature items.

There are some regressions exhibited by our test script test_branch.sh on the janestreet profile (simply run `tools/test_branch.sh -a master -b format-object-fields 'profile=janestreet'`):
```
ocamlformat: Cannot process "code/js_of_ocaml/lib/js_of_ocaml/webGL.ml".
  Please report this bug at https://github.com/ocaml-ppx/ocamlformat/issues.
  BUG: misplaced documentation comments.
ocamlformat: Cannot process "code/js_of_ocaml/lib/js_of_ocaml/webGL.mli".
  Please report this bug at https://github.com/ocaml-ppx/ocamlformat/issues.
  BUG: misplaced documentation comments.
```
(these tests are in`test-extra`)

I see the `Class_type_field.has_doc` and `Class_field.has_doc` functions are much shorter than for str/sig items, maybe some of this code was necessary, but I didn't look more closely.

2020-12-15 10:46 UTC, gpetiot commented on lib/Ast.ml
> +      (* Non_apply is perhaps pessimistic *)
This comment should stay where it was

2020-12-15 10:46 UTC, gpetiot commented on CHANGES.md
> +  + Format objects and classes in a compact way (#1569, @bikallem)
I would say "Format objects and classes consistently with structure and signature items" (as compact only depends on the options), I already renamed the PR

2021-03-09 15:47 UTC, gpetiot commented
I rebased, slightly improved the consistency of the fmt_ functions compared to fmt_structure/signature_item functions, and made sure test_branch.sh doesn't report any issue with the janestreet and the conventional profiles anymore!
It looks ready for me to be merged now, thank you for your contribution!

2021-03-09 19:24 UTC, merged