Consistent break after string constant argument
ocaml-ppx/ocamlformat pull request #2453
Opened 2023-10-03 13:40 UTC by Julow

A break is added after wrapping string constants in argument lists. This break was missing for string constants containing explicit line breaks or format hints.

I consider this to be a bug fix but it's also a requirement for https://github.com/ocaml-ppx/ocamlformat/pull/2445, which removes the code needed to support this formatting.

2023-10-03 14:53 UTC, Julow commented
All the regressions reported by test_branch are intended. This does not break any one-liner.

2023-10-05 10:02 UTC, gpetiot requested changes

2023-10-05 12:18 UTC, Julow commented on lib/Fmt_ast.ml
> +      (fmt_label_arg c ?box (lbl, xarg) $ break_after)
Well spotted. Should be ready to merge now, right ?

2023-10-05 12:20 UTC, gpetiot approved these changes

2023-10-05 12:38 UTC, Julow commented
Then, let's merge!

2023-10-05 12:38 UTC, merged